INSERT INTO Question (ID_question, Intitule, Reponse) VALUES 
 (1, 'Quel est l’objectif principal du bilan carbone ?', 'Mesurer les émissions de gaz à effet de serre d’un produit ou d’une organisation sur une période donnée afin de cibler les leviers de réduction.'),
 (2, 'Qu’est-ce que le Green IT ?', 'Une approche globale visant à réduire l’impact environnemental du numérique, depuis la conception jusqu’à la fin de vie des équipements.'),
 (3, 'Quel gaz est principalement responsable du réchauffement climatique ?', 'Le dioxyde de carbone (CO₂) est le principal gaz à effet de serre émis par les activités humaines.'),
 (4, 'Classez du gaz le plus pollueur au moins pollueur : CH₄, CO₂, N₂, O₂ ?', 'Méthane (CH₄) est plus puissant à court terme que le CO₂, puis viennent N₂ et O₂ qui sont non-actifs comme GES.'),
 (5, 'Quels sont les principaux postes d’émission de GES dans le numérique ?', 'La fabrication des équipements, l’exploitation des data centers et l’acheminement via les réseaux représentent l’essentiel des émissions.'),
 (6, 'Quels sont les scopes d’émission du bilan carbone ?', 'Scope 1 : émissions directes, Scope 2 : émissions indirectes liées à l’énergie, Scope 3 : autres émissions indirectes (fournisseurs, transport...).'),
 (7, 'Le Green IT est-il fondamentalement différent de l’IT for Green ?', 'Non : Green IT et IT for Green visent le même but – verdir l’informatique – mais sont deux façons de le présenter.'),
 (8, 'Quelle est la différence entre Green IT et IT for Green ?', 'Green IT réduit l’impact environnemental du numérique ; IT for Green met le numérique au service d’autres secteurs pour la transition écologique.'),
 (9, 'Quelle est la principale méthode pour évaluer l’impact environnemental d’un produit ?', 'L’analyse du cycle de vie (ACV) permet d’évaluer l’impact à chaque étape, du berceau à la tombe.'),
 (10, 'Quel est l’impact des datacenters ?', 'Ils consomment énormément d’énergie et génèrent beaucoup de chaleur, d’où l’importance de l’optimisation et du refroidissement hybride.'),
 (11, 'Quel est l’impact du cloud sur l’environnement ?', 'Le cloud consomme beaucoup d’énergie pour le stockage et le calcul, mais mutualise les ressources et peut être plus efficient qu’un datacenter isolé.'),
 (12, 'Quelle approche minimise l’impact dès la conception d’un produit ?', 'L’éco-conception intègre l’optimisation des ressources, la durabilité et la fin de vie dès la phase de design.'),
 (13, 'Pourquoi l’obsolescence programmée est-elle un problème écologique ?', 'Elle entraîne un renouvellement rapide des équipements, augmentant déchets et consommation de ressources.'),
 (14, 'Pourquoi les fibres optiques sont-elles préférables au cuivre ?', 'Elles consomment moins d’énergie, offrent de meilleures performances et ont un cycle de vie plus durable.'),
 (15, 'Pourquoi l’ACV est-elle importante ?', 'Elle permet d’évaluer l’impact environnemental global d’un produit sur tout son cycle de vie, pas seulement sa phase d’utilisation.'),
 (16, 'Supprimer ses e-mails réduit-il réellement l’empreinte carbone ?', 'Vrai : les e-mails stockés et transférés génèrent des émissions, donc leur suppression régulière aide à réduire l’empreinte.'),
 (17, 'Quel pourcentage de l’électricité mondiale est consommé par le numérique ?', 'Environ 5,6 % de la consommation électrique mondiale est attribuable aux activités numériques.'),
 (18, 'Quel est l’objectif principal des réseaux verts ?', 'Réduire la consommation d’énergie des infrastructures réseau grâce à des protocoles et du matériel plus efficients.'),
 (19, 'Qu’est-ce que la virtualisation des serveurs ?', 'C’est l’exécution de plusieurs machines virtuelles sur un même serveur physique pour mutualiser et optimiser les ressources.'),
 (20, 'Quel est l’impact principal de la gestion intelligente des équipements réseau ?', 'Elle permet l’optimisation de la consommation énergétique en adaptant dynamiquement l’alimentation selon le trafic.'),
 (21, 'Qu’est-ce que le Green Ethernet (IEEE 802.3az) ?', 'Une norme qui ajuste automatiquement la consommation d’énergie des interfaces Ethernet en fonction du trafic.'),
 (22, 'Quel est le rôle principal du protocole MQTT ?', 'Faciliter la communication légère entre capteurs et serveurs en consommant peu de bande passante.'),
 (23, 'Pourquoi la gestion en mode veille économise-t-elle de l’énergie ?', 'Elle réduit la consommation des équipements inutilisés en les passant en basse énergie lorsqu’ils sont inactifs.'),
 (24, 'Comment la virtualisation réduit-elle la consommation d’énergie ?', 'En consolidant plusieurs machines virtuelles sur un seul serveur, ce qui diminue le nombre de serveurs physiques en fonctionnement.'),
 (25, 'Quel est le principal avantage du protocole Green Ethernet ?', 'Il réduit la consommation d’énergie des commutateurs Ethernet en période d’inactivité.'),
 (26, 'Pourquoi les stratégies de veille et réveil programmés améliorent-elles l’efficacité ?', 'Elles permettent aux équipements de ne consommer de l’énergie que lorsqu’ils en ont réellement besoin.'),
 (27, 'Pourquoi les énergies renouvelables sont-elles cruciales pour les datacenters ?', 'Elles réduisent la dépendance aux fossiles et abaissent fortement l’empreinte carbone des centres de données.'),
 (28, 'Quel impact environnemental majeur des équipements réseau traditionnels ?', 'Ils consomment de l’énergie en continu, augmentant la facture et les émissions de CO₂.'),
 (29, 'Qu’est-ce que le BLE (Bluetooth Low Energy) ?', 'Un protocole sans fil conçu pour consommer très peu d’énergie, idéal pour objets connectés.'),
 (30, 'Quel est l’un des principaux objectifs des Smart Grids ?', 'Adapter la production et la consommation d’énergie en temps réel pour optimiser l’efficacité globale.'),
 (31, 'Comment optimiser un algorithme de routage pour économiser de l’énergie ?', 'En minimisant la distance parcourue par les paquets et en regroupant les flux sur des chemins plus courts.'),
 (32, 'Quelle stratégie réduit la taille des données pour optimiser la transmission ?', 'La compression des données permet de réduire le volume transmis et donc l’énergie consommée.'),
 (33, 'Pourquoi la gestion efficace des équipements connectés réduit-elle leur impact ?', 'Elle éteint ou met en veille les appareils inutilisés et ajuste leur fonctionnement selon les besoins.'),
 (34, 'Comment les centres de données peuvent-ils réduire leur consommation ?', 'En utilisant des énergies renouvelables et des techniques de refroidissement naturel pour diminuer la climatisation.'),
 (35, 'Pourquoi adopter le Free Cooling dans un datacenter ?', 'Pour refroidir les serveurs avec l’air extérieur quand la température le permet, réduisant ainsi la climatisation active.'),
 (36, 'Quel avantage majeur du protocole MQTT dans les réseaux verts ?', 'Il fonctionne même sur des réseaux à faible bande passante grâce à son faible overhead.'),
 (37, 'En quoi consiste un audit énergétique ?', 'C’est une enquête détaillée sur la consommation d’énergie et les pistes d’optimisation.'),
 (38, 'Dans quelle phase collecte-t-on les données primaires d’un audit ?', 'Lors de la phase de pré-audit, on relève les consommations réelles et les conditions d’exploitation.'),
 (39, 'Quelle mesure calcule l’efficacité énergétique d’un datacenter ?', 'Le PUE (Power Usage Effectiveness) est le ratio entre la consommation totale et celle de l’IT.'),
 (40, 'Lequel de ces bénéfices fait partie d’un audit énergétique ?', 'Estimation des coûts d’amélioration et identification des postes de gaspillage.'),
 (41, 'Quel objectif du CUE (Carbon Usage Effectiveness) ?', 'Mesurer les émissions de CO₂ par kWh consommé dans un datacenter pour en réduire l’empreinte.'),
 (42, 'Pourquoi surveiller l’efficacité énergétique en entreprise ?', 'Pour améliorer la rentabilité et limiter l’empreinte carbone en identifiant les axes d’optimisation.'),
 (43, 'Quel élément est essentiel dans une politique d’efficacité IT ?', 'La résilience, c’est-à-dire la capacité à maintenir la performance énergétique en cas de défaillance.'),
 (44, 'Quelle technologie réduit l’empreinte carbone des datacenters ?', 'Les énergies renouvelables couplées à l’IA pour optimiser refroidissement et consommation.'),
 (45, 'Quel principal défi pour des infrastructures IT plus vertes ?', 'Le coût initial d’investissement reste un frein malgré les économies ultérieures.'),
 (46, 'Avantage majeur d’un modèle de virtualisation pour l’énergie ?', 'Une diminution du nombre de serveurs physiques en fonctionnement et donc de la consommation.'),
 (47, 'Impact principal de l’IA sur l’IT durable ?', 'Optimiser l’efficacité énergétique grâce à l’analyse prédictive des charges et du refroidissement.'),
 (48, 'Principale limite des datacenters actuels ?', 'Un accès limité aux énergies renouvelables et au refroidissement naturel.'),
 (49, 'Quel acteur est essentiel pour une IT plus durable ?', 'Tous les employés, de la direction aux utilisateurs, car chacun joue un rôle dans la consommation.'),
 (50, 'Quelle mesure limite le plus l’impact du numérique ?', 'Recycler les équipements et utiliser des énergies renouvelables pour réduire déchets et émissions.'),
 (51, 'Quel appareil analyse les pertes thermiques d’un bâtiment ?', 'Une caméra thermographique permet de visualiser et quantifier les déperditions de chaleur.'),
 (52, 'Inconvénient majeur des énergies fossiles pour datacenters ?', 'Elles émettent beaucoup de CO₂ et dépendent de ressources non renouvelables.'),
 (53, 'Quelle unité mesure la consommation énergétique des serveurs ?', 'Le watt (W) est l’unité standard de puissance consommée par les serveurs.'),
 (54, 'Pourquoi la gestion des fournisseurs est-elle essentielle en Green IT ?', 'Pour garantir un approvisionnement en équipements éco-responsables tout au long de la chaîne.'),
 (55, 'Pourquoi l’optimisation logicielle réduit-elle la consommation ?', 'Elle diminue les opérations CPU inutiles et optimise l’usage mémoire pour réduire l’énergie.'),
 (56, 'Impact du refroidissement par immersion liquide ?', 'Il améliore le transfert de chaleur directement et réduit la consommation des ventilateurs.'),
 (57, 'Pourquoi Python est-il moins performant énergétiquement que C ?', 'Python est interprété, alors que C est compilé en code machine optimisé, donc plus économe.'),
 (58, 'Quel outil mesure l’empreinte carbone d’un cloud public ?', 'Cloud Carbon Footprint fournit des statistiques détaillées sur les émissions du cloud.'),
 (59, 'Avantage du BDD par rapport au TDD ?', 'BDD améliore la communication entre équipes techniques et non-techniques autour des comportements utilisateurs.'),
 (60, 'Quelles pratiques rendent une architecture logicielle durable ?', 'Réduire le stockage inutile et favoriser l’exécution asynchrone pour optimiser ressources et latence.'),
 (61, 'Quelle pratique optimise les requêtes DB ?', 'Ajouter des index sur les champs fréquemment recherchés pour limiter la charge CPU et I/O.'),
 (62, 'Quel est l’objectif d’un logiciel durable ?', 'Réduire l’impact environnemental, social et économique du numérique tout au long du cycle de vie.'),
 (63, 'Trois critères pour évaluer l’efficacité énergétique d’un langage ?', 'Efficacité énergétique, temps d’exécution et utilisation mémoire sont les trois critères clés.'),
 (64, 'Quel est le principe du “YAGNI” ?', '“You Aren’t Gonna Need It” : ne développer que ce qui est nécessaire au moment requis.'),
 (65, 'Pourquoi l’efficacité énergétique est-elle un enjeu majeur en dev ?', 'Elle réduit les coûts d’exploitation et l’empreinte carbone tout en maintenant la performance.'),
 (66, 'Pourquoi les langages compilés sont-ils plus performants en énergie ?', 'Ils optimisent les instructions machine et réduisent le temps d’exécution, donc la consommation.'),
 (67, 'Quels éléments optimiser en base pour réduire la conso ?', 'Utiliser des index et éviter les requêtes inutiles grâce à un cache efficace.'),
 (68, 'Quel principe respecter pour un code efficient ?', 'Minimiser le nombre d’opérations exécutées afin de réduire l’usage CPU et mémoire.'),
 (69, 'Pourquoi éviter les boucles infinies ?', 'Elles consomment inutilement des ressources et peuvent bloquer l’application.'),
 (70, 'Quel facteur contribue le plus à l’empreinte d’une appli web ?', 'Le nombre et la résolution des images chargées impactent fortement la consommation réseau et CPU.'),
 (71, 'Avantage principal d’un site statique vs dynamique ?', 'Un site statique nécessite moins de ressources serveur et génère moins d’appels CPU.'),
 (72, 'Comment améliorer l’efficacité énergétique d’un site web ?', 'Réduire la taille des images, activer le cache et charger les ressources à la demande.'),
 (73, 'Quel est l’impact de la parallélisation sur la consommation ?', 'Elle réduit le temps d’exécution mais peut augmenter la consommation totale des ressources.'),
 (74, 'Pourquoi limiter les animations est une bonne pratique ?', 'Moins d’animations signifie moins d’usage CPU/GPU et donc une meilleure efficacité énergétique.'),
 (75, 'Que permet l’utilisation d’index en base de données ?', 'Accélérer les recherches sur les colonnes ciblées et réduire la charge CPU et I/O.'),
 (76, 'Impact de l’augmentation de la résolution vidéo sur l’empreinte ?', 'Augmente la consommation d’énergie due au traitement et à la bande passante.'),
 (77, 'Inconvénient d’un code récursif vs itératif ?', 'Il consomme plus de mémoire à cause des appels de fonction empilés.');